
name: Run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  Hardhat-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
          registry-url: https://registry.npmjs.org/
      - name: setup and run hardhat tests
        run: |
          echo 'DEPLOY_PK=${{ secrets.DEPLOY_PK }}' > .env
          echo 'DEPLOYER_ADDRESS=${{ secrets.DEPLOYER_ADDRESS }}' > .env
          echo 'INFURA_API_KEY=${{ secrets.INFURA_API_KEY }}' > .env
          yarn 
          yarn compile
          yarn test
